export const GET_CATEGORY = "GET_CATEGORY";
export const SET_SELECTED_OPTION = "SET_SELECTED_OPTION";
export const GET_USER_DATA = "GET_USER_DATA";
export const SET_FORM_DATA = "SET_FORM_DATA";
export const SET_INSPECTION_STATE = "SET_INSPECTION_STATE";
export const GET_CATEGORY_BY_ID = "GET_CATEGORY_BY_ID";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const SET_ADMIN_OPTION = "SET_ADMIN_OPTION";
